export const ApplicationConstant = {
  MELD: "Meld",
  WELCOME: "Welcome to Meld",
  NOTIFIACTIONS: "Notifications",
  BE_IN_CONTROL: "Be in control of your data",
  GUIDE_TO_TRANSPERANCY: "Your guide to data transparency.",
  HOW_DOES_MELD_WORK: "How does Meld work?",
  MODAL_HAS_BEEN_CLOSED: "Modal has been closed.",
  LOGIN_CONNECT_YOUR_FIRST_DATA_SOURCE:
    "LOGIN & CONNECT YOUR FIRST DATA SOURCE",
  ACCEPT_EPSILON_TERMS_CONDITIONS:
    "By continuing you are accepting Eplsion terms and conditions",
  MELD_SHOWS_DIFFERENT_SERVICES_KNOW_ABOUT_YOU:
    "Meld shows you what different services know about you.",
  MELD_ADVICE_CHANGE_PRIVACY_SETTINGS:
    "Meld advices how you can change your privacy settings to match the level of privacy you want.",
  MELD_KEEPS_EYE_AND_ALERTS:
    "Meld keeps an eye on your data and how it is used and alerts on suspicious activities.",
  MELD_DONOT_COPY_DATA:
    "Meld is not copying or storing your data. if you connect services to Meld, it scans the headers of the data," +
    " but not the data itself.",
  ERROR_IN_READING_VALUE_FROM_STORE:
    "Error in getting values from Async Storage",
  ERROR_IN_STORING_VALUE_TO_STORE: "Error in storing to Async storage: ",
  CONNECT_MORE_SERVICE: "Connect more services",
  CONNECT_TO_LEARN_AND_MONITOR:
    "Connect to services to learn what data they collect from you & start monitoring your data",
  E_COM_CONSUMER_SERVICE: "E-com and consumer services",
  REPORT_USE_OF_MY_DATA: "Report the use of My Data",
  NOTIFY_WHEN_ALERTS: "Notify when alerts",
  WEEKLY_SUMMARY: "Weekly Summary",
  MONTHLY_SUMMARY: "Monthly Summary",
  MONITORED_ACTIVITY: "Monitored Activity",
  CONNECTED_SERVICES: "Connected Services",
  REMOVE_FROM_MELD: "REMOVE FROM MELD",
  OKAY_GOT_IT: "OKAY, GOT IT!",
  MELD_ID_FROM_STORAGE: "meldId from storage: ",
  SCRAP_DATA_FROM_STORAGE: "scrappedData from storage: ",
  DATA_ITEMS: "DATA ITEMS",
  WHERE_IS_YOUR_DATA: "Where is your data?",
  LOADING: "Loading...",
  LOREM_IPSUM: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  VIVAMUS:
    "Vivamus augue sapien, egestas in libero vitae, hendrerit lobortisest. Etiam maximus mi diam, id euismod lectus auctor" +
    " vel. Duisblandit a quam non faucibus. Quisque euismod enim quis antefaucibus, ut ullamcorper urna pharetra.",
  WHO_IS_USING_YOUR_DATA: "Who is using your data ?",
  FLAG_ISSUE: "Flag the issue to service provider & community",
  TODAY: "Today",
  IDENTIFY_DATA: "Identify Data",
  PEOPLE_MATTER_MOST: "People Who Matter Most to You",
  ADS_YOU_FIND_USEFULL: "Ads You find most useful",
  COOKIES: "Cookies",
  THINKS_YOU_CREATE: "Thinks You Create or Provide",
  GOOGLE_SEARCH: "Google Search",
  GMAIL: "Gmail",
  YOUTUBE: "Youtube",
  HANGOUTS: "Hangouts",
  GOOGLE_MAPS: "Google Maps",
  GOOGLE_KEEP: "Google Keep",
  ANALYSE_YOUR_DATA_GOOGLE: "Analyzing your data from Google ...",
  INSIGHTS_ABOUT_GOOGLE:
    "Are you ready to hear our insights on what Google knows about you?",
  DONE: "Done!",
  GOOGLE_ACTIVITY:
    "Google Activity helps Google to make services more useful for you, like helping you rediscover the things" +
    " that you've searched for, read and watched",
  PLAY_GROUND: "playground",
  YOU_ARE_IN_GOOD_HANDS: "You are in good hands",
  MELD_COLLECTS_MINIMUM_INFO: "Meld collects only minimum information from you.",
  MELD_BELIEVES_PRIVACY_FUNDAMENTAL_HUMAN_RIGHT: "Meld believes privacy is a fundamental human right.",
  MELD_DESIGNED_TO_PROVIDE_TRANSPARENCY: "Meld is designed to provide transparency and control over your data.",
  CONTINUE: "continue",
  HOW_MELD_WORKS: "How meld works?",
  SIGN_IN_WITH_GOOGLE: "Sign in with Google",
  INVALID_CREDENTIALS: "Invalid Credentials",
  EMAIL_ADDRESS: "Email address",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot password?",
  LOGIN: "login",
  SHOW_PASSWORD: "Show password",
  SIGNUP_FOR_MELD: "Sign up for Meld",
  NO_MELD_ACCOUNT_YET: "No Meld account yet?",
  LOOK_INTO_YOUR_INBOX: "Look into your inbox",
  MELD_HAS_SENT_EMAIL_VERIFICATION: "Meld has sent email verification link to:",
  EDIT_EMAIL: "Edit email",
  GO_TO_EMAIL_AND_CLICK: "Go to your email and click",
  VERIFY_EMAIL: "Verify email",
  DID_NOT_RECEIVE_THE_LINK: "Did not receive the link?",
  IT_CAN_TAKE_UPTO_2MIN: "It can take up to 2 mins to arrive.",
  TERMS_OF_SERVICE: "Terms of service",
  MELD_IS_FULLY_TRANSPARENT_ABOUT_DATA: "Meld is fully transparent about the data we collect about you.",
  ALL_YOUR_INFO_STORED_ENCRYPTED: "All your information is stored and handled confidentially and encrypted.",
  YOUR_DATA_NOT_SOLD_TO_3RD_PARTY: "Your data is not sold to 3rd parties.",
  WE_WILL_KEEP_YOU_INFORMED: "We will keep you informed what data we are collecting as you use the service.",
  SIGNING_UP_WITH_MELD: "E.g.  Signing up with Meld we collect",
  YOUR_MELD_EMAIL_ADDRESS: "Your e-mail address",
  YOUR_MELD_PASSWORD: "Your Meld password",
  BY_CONTINUING_I_AGREE_TO_MELD: "By continuing I agree to Meld",
  PRIVACY_POLICY: "Privacy policy.",
  AND_WITH_SPACE: " and ",
  WELCOME_TO_MELD: "Welcome to Meld!",
  YOUR_DATA_IS_YOURS_TO_CONTROL: "Your data is yours to control.",
  ACCOUNT_ALREADY_EXISTS: "Account already exists",
  EMAIL_IS_ALREADY_REGISTERED_DESC: "This email is already registered to Meld.\n\nUse the login instead."
};
