# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# git add . && git commit -m "commit 29" && git push origin development

name: CI/CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '\[[^]]+\] .+$'
        flags: 'gm'
        error: 'Your first line has to contain a commit type like "[BUGFIX]".'
    - name: Check Line Length
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '^[^#].{74}'
        error: 'The maximum line length of 74 characters is exceeded.'
        excludeDescription: 'true' # optional: this excludes the description body of a pull request
        excludeTitle: 'true' # optional: this excludes the title of a pull request
        checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
        accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
    - name: Check for Resolves / Fixes
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '^.+(Resolves|Fixes): \#[0-9]+$'
        error: 'You need at least one "Resolves|Fixes: #<issue number>" line.'
    - name: Build
    - run: yarn install
    - name: Unit Test
    - run: yarn test --silent
    - name: Lint
    - run: yarn eslint src
